# Default values for homing-pigeon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
updateStrategy: null

messageBufferLen: 400
ackBufferLen: 200
consumerId: null

nameOverride: ""
fullnameOverride: ""

podLabels: {}
podAnnotations: {}
tplPodAnnotations: null
# tplPodAnnotations: |
#   version: {{ .Release.Version }}
image:
  repository: softonic/homing-pigeon
  tag: 0.1.0
  pullPolicy: IfNotPresent

passthrough:
  repository: softonic/hp-pass-middleware
  tag: 0.1.0
  pullPolicy: IfNotPresent

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
initContainers: []
tplInitContainers: null
# tplInitContainers: |
#   - name: {{ .Release.Name }}-myinitcontainer
#     command:
#     - curl
#     - {{ .Values.writer.elasticsearch.host }}
extraContainers: []
caCerts: []
extraVolumes: []
tplExtraVolumes: null
# tplExtraVolumes: |
#   - name: myconfig
#     configMap:
#       name: {{ .Release.Name }}-config

extraVolumeMounts: []

reader:
  rabbitmq:
    enabled: false
    consumerName: ""
    url: ""
    ssl: false
    caCertName: ""
    deadLettersExchangeName: ""
    deadLettersQueueName: ""
    exchangeName: ""
    exchangeType: ""
    exchangeInternal: "false"
    outerExchangeName: ""
    outerExchangeType: ""
    outerExchangeBindingKey: ""
    queueName: ""
    queueBindingKey: "#"
    qos:
      prefetchCount: 0

writer:
  elasticsearch:
    enabled: false
    host: ""
    flushMaxSize: 100
    flushMaxIntervalMs: 5000

middlewares: []
#### Config example
#  - name: middlewareName
#    repository: softonic/hp-pass-middleware
#    tag: latest
#    pullPolicy: IfNotPresent
