{{- if .Values.extraConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homing-pigeon.fullname" . }}-extra
  labels:
    app.kubernetes.io/name: {{ include "homing-pigeon.name" . }}
    helm.sh/chart: {{ include "homing-pigeon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- range $key, $val := .Values.extraConfig }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}