{{- if .Values.flags }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homing-pigeon.fullname" . }}-flags
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
data:
{{- range $key, $val := .Values.flags }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}